steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['mv', '*', 'html']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['compute', 'scp', '--recurse', 'html', 'instance-1:/var/www/html' , '--zone','asia-northeast1-a']